baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Google Graveyard'
theme = "killedbyx"


[params]
copyright = "&copy; 2010 - {currentYear} Google. All rights reserved."
companyName = "Google"
header = 'Killed by Google'
deathLogo = "images/tombstone.svg"
altDeathLogo = "images/tombstone-alt.svg"
githubIcon = "images/github.svg"

